Wikiped/Wikiped/Controllers/ClanciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wikiped.Models;
using Wikiped.DBBL.DAL;
using Wikiped.DBBL.BLL;
using System.Web.Script.Serialization;
using System.IO;
using System.Drawing;
namespace Wikiped.Controllers
{
    public class ClanciController : Controller
    {
        //
        // GET: /Clanci/

        public ActionResult Index()
        {
            ClanciServisObrada c = new ClanciServisObrada();
            ViewBag.Search = false;
            return View(c.getAllClanci());
        }
        [HttpPost]
        public ActionResult Index(string btnSearch, string search)
        {
            List<LuceneObject> clanci;
            clanci = LucenePt.Search(search).ToList();
            if (clanci != null)
            {
                clanci = clanci.Where(x => x.IsQuestion == false).ToList();
                if (clanci.Count == 0)
                {
                    ViewBag.HasResult = false;
                }
                else
                {
                    ViewBag.HasResult = true;
                }
            }
            else
            {
                ViewBag.HasResult = false;
            }

            ViewBag.Clanci = clanci;
            ViewBag.Search = true;
            return View();
        }

        public ActionResult Edit(int id)
        {
            ClanciServisObrada c = new ClanciServisObrada();
            return View(ClanciServisObrada.getClanakById(id));
        }
        public JsonResult MogucnostGlasanja(int clanakId)
        {
            if (Session["Korisnik"] == null)
            {
                return Json(new
                {
                    Success = false,
                    Message = "* Morate biti logovani",
                    color = ""
                });
            }
            else
            {
                Korisnici kor = Session["Korisnik"] as Korisnici;
                using (Spajanje sp = new Spajanje())
                {
                    OcjenaKorisnici glasanje = (from co in sp.Context.OcjenaKorisnici
                                                where co.ClanakID == clanakId && co.KorisnikID == kor.KorisnikID
                                                select co).FirstOrDefault();

                    if (glasanje != null)
                    {
                        return Json(new
                        {
                            Success = false,
                            Message = "* Glasali ste za ovaj clanak",
                            color = ""

                        });
                    }



                }

            }
            return Json(new
            {
                Success = true,
                Message = "",
                color = ""
            });
        }
        public ActionResult ClanciPregled(int clID)
        {
            ClanciServis clanak = ClanciServisObrada.getClanakById(clID);
            List<ClanakProsjek> preporukaTemp = preporukaItembase(clID);
            List<int> preporukaIds = (from p in preporukaTemp select p.ClanakId).ToList();


            ViewBag.Preporuka = ClanciServisObrada.getClanciByIds(preporukaIds);
            List<string> Words = getWordForWiki(clID);

            ExternalIntegration t = new ExternalIntegration();

            List<Wiki> clanciWiki = new List<Wiki>();
            foreach (string its in Words)
            {
                clanciWiki.AddRange(t.SearchWikipedia(its));
            }
            clanciWiki = clanciWiki.Take(5).ToList();

            ViewBag.PreporukaWiki = clanciWiki;
            Korisnici kor = Session["Korisnik"] as Korisnici;
            if (kor != null)
            {
            List<ClanciContains> PrepKolab= preporukaColaborative(kor.KorisnikID);
            ViewBag.PreporukaKorisnici = getKorisniciByIds(PrepKolab);
            }
            else{
                ViewBag.PreporukaKorisnici = null;
            }

            

            


            return View(clanak);
        }
        public ActionResult zloupotreba(int zlID)
        {
            try
            {
                string poruka = "";
                bool uspjeh = false;
                if (Session["Korisnik"] != null)
                {
                    using (Spajanje s = new Spajanje())
                    {
                        Zloupotrebe zl = (from z in s.Context.Zloupotrebe where z.KomentarID == zlID select z).FirstOrDefault();

                        if (zl == null)
                        {

                            zl = new Zloupotrebe();
                            zl.KomentarID = zlID;
                            Korisnici kor = Session["Korisnik"] as Korisnici;
                            zl.KorisnikID = kor.KorisnikID;
                            s.Context.Zloupotrebe.AddObject(zl);
                            s.Context.SaveChanges();

                            uspjeh = true;
                            poruka = "Uspješno prijavljen komentar";
                            //spremi u bazu i vrati stanje
                        }
                        else
                        {
                            poruka = "Prijavili ste ovaj komentar";
                            //error vec ste glasali
                        }
                    }
                }
                else
                {
                    //error morate se logovati
                    poruka = "Morate se prijaviti";
                }

                return Json(new
                {
                    success = uspjeh,
                    message = poruka


                });
            }
            catch (Exception)
            {

                return null;
            }


        }
        public JsonResult SetOcjena(int clanakId, double rating)
        {
            try
            {
                dynamic mogucnost = MogucnostGlasanja(clanakId).Data;

                if (mogucnost.Success == false)
                {
                    return Json(mogucnost);
                }
                Korisnici kor = Session["Korisnik"] as Korisnici;
                using (Spajanje s = new Spajanje())
                {
                    OcjenaKorisnici oc = new OcjenaKorisnici();
                    oc.KorisnikID = kor.KorisnikID;
                    oc.ClanakID = clanakId;
                    oc.Ocjena = (rating / 2);
                    s.Context.OcjenaKorisnici.AddObject(oc);


                    Clanci clanakTemp = (from c in s.Context.Clanci where c.ClanakID == clanakId select c).FirstOrDefault();
                    if (clanakTemp.Ocjenjeno > 0)
                    {
                        int brojOcjena = (int)clanakTemp.Ocjenjeno;
                        double ProsOcjena = (double)clanakTemp.Popularnost;
                        double novaProsjecna = ((ProsOcjena * (double)brojOcjena) + (double)oc.Ocjena) / (brojOcjena + 1);

                        clanakTemp.Popularnost = novaProsjecna;
                        clanakTemp.Ocjenjeno++;

                    }
                    else
                    {
                        clanakTemp.Popularnost = (double)oc.Ocjena;
                        clanakTemp.Ocjenjeno++;
                    }
                    s.Context.SaveChanges();

                    return Json(new
                    {
                        Success = true,
                        Message = "Uspjesno ste glasali",
                        Result = new { Rating = (clanakTemp.Popularnost * 2), Raters = ("(od " + clanakTemp.Ocjenjeno + " korisnika)") },
                        color = ""

                    });
                }
                //PostModel post = Engine.Posts.SetRating(id, rating);

            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Success = false,
                    Message = ex.Message
                });
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult NoviKomentar(string text, int clanakID)
        {
            try
            {

                using (Spajanje s = new Spajanje())
                {
                    Korisnici k = Session["Korisnik"] as Korisnici;
                    if (k == null)
                    {
                        return Json(new
                        {
                            Success = false,
                            poruka = "* Morate biti logovani"
                        });
                    }
                    else
                    {
                        if (text.Length > 11)
                        {

                            ClanciServisObrada.InsertComment(clanakID, k, text);
                            return Json(new
                            {
                                tekst = text,
                                datum = DateTime.Now.ToString(),
                                korisnik = k.UserName,
                                poruka = "Uspješno objavljen komentar",
                                Success = true
                            });
                        }
                        else
                        {
                            return Json(new
                            {
                                Success = false,
                                poruka = "* Morate unijeti minimalno 5 slova"
                            });

                        }

                    }

                }
            }
            catch (Exception)
            {
                return Json(new
                {
                    Success = false,
                    poruka = "* Desila se pogreška"
                });

            }

        }

        public ActionResult Create()
        {
            Korisnici kor = Session["Korisnik"] as Korisnici;
            if (kor != null)
            {
                List<TagVrste> tgs;

Wikiped/Wikiped/Views/Clanci/ClanciPregled.cshtml
@model Wikiped.Models.ClanciServis
@using Wikiped.Models
@using Wikiped.DBBL.DAL;
@{
    ViewBag.Title = "ClanciPregled";
    Layout = "~/Views/Shared/Pocetna.cshtml";
}
<script src="/Script/clanci.js" type="text/javascript"></script>
<script src="/Script/tiny_mce/tiny_mce.js" type="text/javascript"></script>
<script src="/Script/pitanja.js" type="text/javascript"></script>

<div class="clanak-details-head">
@if (Model.slika != null)
{
    <img src="@Html.DisplayFor(model => model.slika)" alt="@Html.DisplayNameFor(model => model.slika)" class="clanak-slika" />
}
    <div class="clanak-details-opis">
        <div class="clanak-details-namefor">
            Naslov</div>
        @Html.DisplayFor(model => model.naslov)</div>
    <div class="clanak-details-opis">
        <div class="clanak-details-namefor">
            Kreirano</div>
        @Model.datum - @Model.korisnik</div>
    <div class="clanak-details-opis">
        <div class="clanak-details-namefor">
            Ocjena</div>@Html.Ratings(Model.popularnost, Model.ClanakId, Model.ocjena)<div class="clanak-details-namefor-error">
            </div>
    </div>
    
    <div class="clanak-details-wrap-tag">
        <div class="clanak-details-namefor">
            Tagovi</div>
            @foreach (Tags it in Model.tagovi)
            {
                <a href="/Tag/Details/?name=@it.Ime" class="post-tag" title="" rel="tag">@it.Ime</a>
            }

        </div>
</div>
<div class="clanak-details-preporuka">

<div class="clanak-preporuka-naslovP">Preporuka - Item based</div>

@foreach (ClanciServis pr in ViewBag.Preporuka)
{
    

<div class="clanak-preporuka-naslov">@pr.naslov</div>
<div class="clanak-preporuka-text">
        @if (pr.slika != "")
        {
            if(pr.slika != null)
            {
            <img src="@pr.slika" alt="wikitest" class="clanak-preporuka-slika" />
            }
        }
            @pr.tekst
            <div class="clanak-read-more">
                @Html.ActionLink("Procitaj vise...", "ClanciPregled", new { clID = pr.ClanakId })
                
                </div>
           
      
        </div>
}
@if (ViewBag.PreporukaKorisnici != null)
{
<div class="clanak-preporuka-naslovP" style="border-top-left-radius:0px; border-top-right-radius:0px; ">Preporuka - collaborative</div>
foreach (Korisnici pr in ViewBag.PreporukaKorisnici)
{
<div class="clanak-preporuka-naslov" style="background:#daaf85;"><a href="/users/details/@pr.KorisnikID">@pr.UserName</a></div>
}
}


<div class="clanak-preporuka-naslovP" style="border-top-left-radius:0px; border-top-right-radius:0px; ">Wikipedia preporuka</div>
@foreach (Wiki pr in ViewBag.PreporukaWiki)
{
    

<div class="clanak-preporuka-naslov" style="background: rgb(240, 222, 205);">@pr.Name</div>
<div class="clanak-preporuka-text">
            @pr.Description
            <div class="clanak-read-more">
            <a href="@pr.Url">Procitaj vise...</a>
               
                </div>
           
      
        </div>
}


</div>
<div class="clanak-details-content">@MvcHtmlString.Create(Model.tekst)
    <div class="mainComment-Clanci">
        <div class="clanci-head">
            Vaš komentar</div>
        <div class="wmd-panel">
            <textarea class="myTextEditor" style="width: 400px" id="wmd-input" name="txtComment">
                    </textarea>
        </div>
        <div class="clanci-poruka-poslano">
        </div>
        <div class="mainCommentBtn">
            Vaš komentar
            </div>
        <input type="hidden" id="clanakIDs" value="@Model.ClanakId" />
        @foreach (KomentariServis kom in Model.komentariLista)
        {
              
                    
            <div class="clanak-komentar-wraper">
                <div class="clanak-komentar-evidencija">
                    <div class="clanak-komentar-ko" style="font-weight: bold">
                        @kom.Korisnik</div>
                    <div class="clanak-komentar-ko">
                        @kom.datum</div>
                </div>
                @{
            string prikaz = "";
            if (kom.zloupotreba > 0)
            {
                prikaz = "none";

            }
            else
            {
                prikaz = "block";

            }
                } 
                @if (kom.zloupotreba > 0)
                {
                    <div  class="clanak-komentar-tekst-skriven" style="color:#7d7d7d; font-style:italic">Komentar je sakriven. <div id="@string.Format("sk{0}", @kom.komentarID)" class="clanci-prikazi-sakriven">Prikaži!</div> </div>
                    
                }
                <div id="@string.Format("cltx{0}", @kom.komentarID)" class="clanak-komentar-tekst" style="display:@prikaz">
                <div id="@string.Format("zl{0}", @kom.komentarID)" class="clanci-komentar-zloupotreba"></div>
                
                    @MvcHtmlString.Create(kom.tekst)
                    
                    </div>
                     @if (kom.zloupotreba < 1)
                     {
                <div class="clanak-komentar-dojam">
                
                    <a id="@string.Format("cl{0}", @kom.komentarID)" class="clanak-greska" title="Prijavi komentar"></a>
                </div>
                     }
            </div>
        
        }
    </div>
</div>
<script type="text/javascript">
    $("document").ready(function () {

        $(".clanci-prikazi-sakriven").click(function () {
            var id = this.id.replace("sk", "");

            if ($(this).text() == "Prikaži!") {

                $("#cltx" + id).show();
                $(this).text("Sakrij!");
            }
            else {
                $("#cltx" + id).hide();
                $(this).text("Prikaži!");
            }


        });
        $(".clanak-greska").click(function () {
            zloupotreba(this.id);


        });
        $(".mainCommentBtn").click(function () {

            var tekst = tinyMCE.activeEditor.getContent();

            var clanakid = $("#clanakIDs").val();

            NoviKomentar(tekst, clanakid);

        });

        function setRating(span, rating) {
            var slike = span.find('img');
            for (var i = 0; i < slike.length; i++) {

                var value = parseFloat($(slike[i]).attr("value"));
                var imgSrc = $(slike[i]).attr("src");

                if (value <= rating) {
                    $(slike[i]).attr("src", imgSrc.replace("OFF.gif", "ON.gif"));
                }
                else
                    $(slike[i]).attr("src", imgSrc.replace("ON.gif", "OFF.gif"));
            }
        }

        $(".star").mouseover(function () {
            var span = $(this).parent("span");
            var newRating = $(this).attr("value");
            setRating(span, newRating);

            fadeError();
        });
        $(".star").mouseout(function () {
            var span = $(this).parent("span");
            var rating = span.attr("rating");

            setRating(span, parseFloat(rating.toString()));
        });


        $(".star").click(function () {
            var provjeraOcjene = $(".clanak-details-namefor-error");

            var span = $(this).parent("span");
            var newRating = $(this).attr("value");
            var postID = span.attr("post");
            var text = span.children("span");
            $.post("/Clanci/SetOcjena", { clanakId: postID, rating: newRating },
        function (obj) {
            if (obj.Success) {

                span.attr("rating", obj.Result.Rating);
                setRating(span, obj.Result.Rating);
                $(".ocjene-text").text(obj.Result.Raters);
                provjeraOcjene.css("color", "#0b7100");
            }
            else {
                provjeraOcjene.css("color", "#ee0101");

            }
            provjeraOcjene.text(obj.Message);
            fadeError(provjeraOcjene);

        }
    );

        });

        tinyMCE.init({
            // General options
            //mode: "textareas",
            mode: "specific_textareas",
            title: 'Make h1',
            width: "599px",
            editor_selector: "myTextEditor",
            theme: "advanced",
            plugins: "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
            // Theme options
            theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|formatselect,fontselect,fontsizeselect,|,undo,redo,|,forecolor,backcolor,|,emotions,fullscreen",

            //theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: false,
            // Skin options
            skin: "o2k7",
            //skin_variant: "silver", black

            // Example content CSS (should be your site CSS)
            //content_css: "css/example.css",

            // Drop lists for link/image/media/template dialogs
            //        template_external_list_url: "js/template_list.js",
            //        external_link_list_url: "js/link_list.js",
            //        external_image_list_url: "js/image_list.js",
            //        media_external_list_url: "js/media_list.js",

            // Replace values for the template plugin
            template_replace_values: {
                username: "Some User",
                staffid: "991234"
            }
        });

    });
</script>

Wikiped/Wikiped/Views/Clanci/Create.cshtml
@model List<Wikiped.DBBL.DAL.TagVrste>
@using Wikiped.DBBL.DAL;
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Pocetna.cshtml";
}


<script src="/Script/tiny_mce/tiny_mce.js" type="text/javascript"></script>
<script src="../../Script/clanci.js" type="text/javascript"></script>
<link href="/Script/autocomplete/css/jquery.tagit.clanak.css" rel="stylesheet" type="text/css" />
<script src="/Script/autocomplete/tag-it.js" type="text/javascript"></script>
<script src="/Script/autocomplete/autocomplete-tags.js" type="text/javascript"></script>
<link href="../../Script/chosen/chosen.css" rel="stylesheet" type="text/css" />
<script src="../../Script/chosen/chosen.jquery.js" type="text/javascript"></script>
<style type="text/css">
.clanak-details-content
{
    margin-right: 35px;
}
</style>
<div class="clanci-create-head">
<div id="btnNoviClanak" class="clanak-create-meni">Novi clanak</div>
<div id="btnMojiClanci" class="clanak-create-meni">Moji clanci</div>
</div>



@using (Html.BeginForm("create","Clanci",FormMethod.Post,new {enctype = "multipart/form-data" }))

{
<div class="clanak-details-content">
<div id="mojClanakSkriven" class="clanak-skriveno">
    <div class="clanci-head">Vasi clanci</div>
    <select data-placeholder="Odaberite clanak..." name="mojClanak" id="mojClanak" class="clanak-create-textBox">
    <option value="0"></option> 
         @foreach (var cls in ViewBag.clanci)
    {
        <option value="@cls.ClanakID">@cls.Naslov</option>
    }
    </select>
    </div>
<div id="NaslovKreiraj" class="clanak-otkriveno">
<div class="clanci-head">
<div class="clanak-head-texts">Naslov</div>

<div id="greskaNaslov" class="clanak-naslovi-greska"></div>

</div>
<input id="txtNaslov" name="naslov" type="text" class="clanak-create-textBox" />
</div>

<div id="KategorijaVis" class="clanak-otkriveno">
<div class="clanci-head">Kategorija</div>

    <select name="kategorija" id="ddlkategorije" class="clanak-create-textBox">
    <option value="0"></option> 
    @foreach (var tg in Model)
    {
        <option value="@tg.TagVrstaID">@tg.Opis</option>
    }
        
    </select>
    </div>


    <div id="sKategorijaVis" class="clanak-skriveno">
    <div id="slKat"class="clanci-head"></div>
    <select name="slicnaKat" id="ddlSlkategorije" class="clanak-create-textBox">
    <option value="0"></option> 
         @foreach (var tg in Model)
    {
        <option value="@tg.TagVrstaID">@tg.Opis</option>
    }
    </select>
</div>
  <div class="clanci-head">
           <div class="clanak-head-texts">Vaš tekst</div> 
            <div id="greskaText" class="clanak-naslovi-greska"></div>
            </div>
        
            <textarea name="tekst" class="clanak-create-textArea" id="txttext"></textarea>
        

<div class="clanci-head">Slika</div>
<input name="slika" type="file" class="clanak-create-textBox" name="fuSlika" />

<div class="clanci-head">Tagovi</div>
<input name="tagovi" type="text" class="clanak-create-textBox" id="txtTagsClanci"/>
<input id="update" name="update" type="hidden" value="false"/>
<input id="clids" name="clids" type="hidden" value="0"/>

<input id="novaKat" name="novaKat" type="hidden" value=""/>

<input id="btnObjava" class="mainCommentBtn" type="submit" value="Objavi clanak" />
    <input id="btnBrisanjeC" class="mainCommentBtnB" type="button" style="display:none" value="Obrisi clanak"  />
<div id="brisanjeGreska" class="clanak-brisanje-greska"></div>


</div>
}

<div class="sidebar-right">
        <div style="font-size: 15px;font-weight: bold;margin-bottom: 10px;font-style: italic;color: rgb(4, 54, 90)!important;">Najpopularni tagovi</div>
        <div id="recent-tags-list">
        @foreach (var tag in ViewBag.Tagovi)
        {
                        <a href="/Tag/Details/?name=@tag.Name" class="post-tag" title="" rel="tag">@tag.Name</a><span
                class="item-multiplier"><span class="item-multiplier-x">×</span>&nbsp;<span class="item-multiplier-count">@tag.CountT</span></span><br>
        }
        </div>
    </div>    


<script type="text/javascript">
    $("document").ready(function () {
        $(".mainCommentBtn").button();
        $(".mainCommentBtnB").button();
        $("#mojClanak").change(function () {
            getClanakByIDs($("#mojClanak").val());

            $("#btnObjava").removeAttr('disabled');
            $("#btnBrisanjeC").removeAttr('disabled');
        });
        $("#btnBrisanjeC").click(function () {
            brisanjeClanka($("#mojClanak").val());


        });
        $("#btnMojiClanci").click(function () {


            $("#mojClanakSkriven").slideDown();
            $("#update").val(true);
            $("#btnObjava").val("Uredi clanak");
            $("#btnBrisanjeC").show();
            $("#btnObjava").attr('disabled', 'disabled');
            $("#btnBrisanjeC").attr('disabled', 'disabled');

        });
        $("#btnNoviClanak").click(function () {


            $("#mojClanakSkriven").slideUp();
            $("#update").val(false);
            $("#btnObjava").val("Objavi clanak");
            $("#btnBrisanjeC").hide();

        });

        $("form").submit(function () {
            if (provjeraUnosa() == false) {
                $(".clanak-naslovi-greska").fadeIn();
            }

            return provjeraUnosa();
        });


        $("#ddlkategorije").chosen({ no_results_text: "Kategorija ne postoji" + '<div id="btnNovaKats" class="clanak-nova-kategorija">Dodaj kategoriju</div>' });
        $("#ddlSlkategorije").chosen({ no_results_text: "Trenutno odabrana kategorija: Ostalo - " });
        $("#mojClanak").chosen({ no_results_text: "Trenutno nema clanka - " });
        function provjeraUnosa() {
            var tekst = $("#txttext").val();
            if (tekst.length > 50) {
                $("#greskaText").text("");
                if ($("#txtNaslov").val().length > 10) {
                    return true;
                }
                else {

                    $("#greskaNaslov").text("* Unesite 10 ili vise slova!");
                    return false;
                }

            }
            else {

                $("#greskaText").text("* Unesite 50 ili vise slova!");
                if ($("#txtNaslov").val().length < 10) {
                    $("#greskaNaslov").text("* Unesite 10 ili vise slova!");
                } else {

                    $("#greskaNaslov").text("");

                }

                return false;


            }

        }
        $("#btnNovaKats").live('click', function () {
            provjeraUnosa();
            var novaKategorija = $(".no-results").find("span").text();
            $("#novaKat").val(novaKategorija);

            $("#KategorijaVis").hide();
            $("#slKat").text("Odaberite slicnu kategoriju za " + novaKategorija + " - ").append("<div class='clanci-change'>Promjeni</div>");
            $("#sKategorijaVis").show();


        });
        $(".clanci-change").live('click', function () {
            $("#sKategorijaVis").hide();
            $("#KategorijaVis").show();
        });


    });

</script>

Wikiped/Wikiped/Views/Clanci/Index.cshtml
@model List<Wikiped.Models.ClanciServisObrada>
@using Wikiped.Models
<script src="../../Script/jquery.masonry.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $("document").ready(function () {
        $('#CanciSvi').masonry({
            itemSelector: '.clanak-wraper'
        });
        $('#Pretraga').button();
    });
</script>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Pocetna.cshtml";
}
@using (Html.BeginForm())
{
    <div class="clanak-text-search-txt" style="background-color: white; -webkit-box-shadow: 1px 5px 4px white;
        box-shadow: 0 3px 3px white;">
        <div id="searchPitanja">
            <div class="form-row" style="margin-bottom: 35px;">
                <label style="margin-right: 24px;">
                    Pretraga</label>
                <input type="text" class="title" name="search" style="width: 545px;" />
                <input type="submit" name="btnSearch" value="Pretraga" id="Pretraga" style="width: 82px;" />
            </div>
        </div>
    </div>
    }
    @if (ViewBag.Search == false)
    {
    <div class="ClanciSviWrap" id="CanciSvi">
        @foreach (var it1 in Model)
        {
            <div class="clanak-wraper @(it1.klasa)">
                @foreach (var it2 in it1.ClanciOrig)
                {

                    <div class="clanak-naslov  @(it1.klasa)">
                        @Html.DisplayFor(modelItem => it2.naslov)
                    </div>
            
                    <div class="clanak-text">
                        @if (it2.slika != "")
                        {
                            if (it2.slika != null)
                            {
                            <img src="@Html.DisplayFor(modelItem => it2.slika)" alt="wikitest" class="clanak-slika" />
                            }
                        }
                        @MvcHtmlString.Create(it2.tekst)
                        <div class="clanak-read-more">
                            @Html.ActionLink("Procitaj vise...", "ClanciPregled", new { clID = it2.ClanakId })
                        </div>
                        <div class="Ocjene-Wraper">@Html.Ratings(it2.popularnost, it2.ClanakId, it2.ocjena)<div
                            class="clanak-komentari">
                            Komentari (@it2.komentari)</div>
                        </div>
                    </div>

                }
            </div>
   
        }
    </div>
    }
    else
    {
    <div class="ClanciSviWrap" id="CanciSvi">
        @foreach (var item in ViewBag.Clanci)
        {
            <div class="clanak-wraper smeda">
                    <div class="clanak-naslov  PlavaT">
                       @item.Name
                    </div>
                    <div class="clanak-text">
                         @if (item.Description.Length > 551)
                    { @item.Description.Substring(0, 550) }
                    else
                    { @item.Description }
                        <div class="clanak-read-more">
                            @Html.ActionLink("Procitaj vise...", "ClanciPregled", new { clID = item.Id })
                        </div>
                    </div>
            </div>
        }
        @if (ViewBag.HasResult == false)
        {
              <div class="question-summary narrow">
                <div class="summary">
                    <h3>
                        <a class="colorBlue" href="" style="text-decoration:none!important;">Nema rezultata za datu pretragu...</a></h3>
                </div>
            </div>
        }
    </div>
    }