Wikiped/Wikiped/Controllers/PocetnaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wikiped.DBBL.BLL;
using Wikiped.DBBL.DAL;

namespace Wikiped.Controllers.Register
{
    public class PocetnaController : Controller
    {
        //
        // GET: /Pocetna/

        public ActionResult Index()
        {
            Korisnici kor = Session["Korisnik"] as Korisnici;
            ViewBag.logiran = kor.UserName.ToString();

            return RedirectToAction("Index","Index");
        }
        public ActionResult OProjektu()
        {
       
            return View();

        }
        public ActionResult odjava()
        {
           Session.RemoveAll();
           return RedirectToAction("Index", "Index");
        }
        [ChildActionOnly]
        //[CustomAuthorize(Roles = Wikiped.Models.CustomAuthorizeAttribute.SiteRoles.Admin | Wikiped.Models.CustomAuthorizeAttribute.SiteRoles.Helpdesk)]
        public ActionResult Prijavljen()
        {
            Korisnici kor = Session["Korisnik"] as Korisnici;
            if (kor != null)
            {
                return PartialView("Prijavljen", kor);
            }
            else
            {
                return PartialView("NePrijavljen");
            }

        }

    }
}

Wikiped/Wikiped/Views/Pocetna/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Pocetna.cshtml";
}

Wikiped/Wikiped/Views/Pocetna/NePrijavljen.cshtml
 <link href="../../css/Register.css" rel="stylesheet" type="text/css" />
 
 <div id="btnPrijavise" class="logintext">Prijava</div>
        <div class="loginSlika">
        </div>
        
        <div id="RegID" class="regtext">Registracija</div>
        <div class="regSlika">
        </div>

Wikiped/Wikiped/Views/Pocetna/OProjektu.cshtml
@model List<Wikiped.DBBL.DAL.TagVrste>
@using Wikiped.DBBL.DAL;
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Pocetna.cshtml";
}


<script src="/Script/tiny_mce/tiny_mce.js" type="text/javascript"></script>
<script src="../../Script/clanci.js" type="text/javascript"></script>
<link href="/Script/autocomplete/css/jquery.tagit.clanak.css" rel="stylesheet" type="text/css" />
<script src="/Script/autocomplete/tag-it.js" type="text/javascript"></script>
<script src="/Script/autocomplete/autocomplete-tags.js" type="text/javascript"></script>
<link href="../../Script/chosen/chosen.css" rel="stylesheet" type="text/css" />
<script src="../../Script/chosen/chosen.jquery.js" type="text/javascript"></script>
<style type="text/css">
.clanak-details-content
{
    margin-right: 35px;
}
</style>
<div class="clanci-create-head" style="font:18px; padding:3px;height:28px;width: 929px;">
Informacije
</div>



<div class="clanak-details-content" style="width:925px !important">

<div id="NaslovKreiraj" class="clanak-otkriveno">

<div class="clanci-head" style="width:917px !important">
<div class="clanak-head-texts">Tema</div>
</div>
<div class="clanak-OProjektu-opis">Wiki</div>

<div class="clanci-head" style="width:917px !important">
<div class="clanak-head-texts">Grupa</div>
</div>
<div class="clanak-OProjektu-opis">Jahorina</div>

<div class="clanci-head" style="width:917px !important">
<div class="clanak-head-texts">Tim</div>
</div>
<div class="clanak-OProjektu-opis">Avdo Hercegovac, Admir Mehanović, Stanko Dugandžić</div>

</div>


</div>



<script type="text/javascript">
</script>

Wikiped/Wikiped/Views/Pocetna/Prijavljen.cshtml
@model Wikiped.DBBL.DAL.Korisnici
<link rel="stylesheet" type="text/css" href="../../css/Prijavljen.css" />

<a href=@Url.Action("odjava","Pocetna")>
<div id="btnOdjava1" class="OkolicaMenijaPri">
<div class="headSliklogof"></div>
<div id="rgText1"  class="headTextPP">@Model.UserName</div>
<div class="headTextPodMeni2">Odjava</div>
</div>
</a>

<div id="btnOdjava2" class="OkolicaMenijaPri">
<a href="/pitanja/create">
<div class="headSlikPitanje"></div>
<div id="rgText2"  class="headTextPP" runat="server">Pitanja</div>
<div class="headTextPodMeni2">Evidencija pitanja</div>
</a>
</div>

<div id="btnOdjava3" class="OkolicaMenijaPri">
<a href="/clanci/create">
<div class="headSlikWiki"></div>
<div id="rgText3"  class="headTextPP" runat="server">Wiki</div>
<div class="headTextPodMeni2">Evidencija clanaka</div>
</a>
</div>


<div id="btnOdjava4" class="OkolicaMenijaPri">
<a href="/Pocetna/OProjektu">
<div class="headSlikProfil"></div>
<div id="rgText4"  class="headTextPP" runat="server">O projektu</div>
<div class="headTextPodMeni2">Pregled informacija</div>
</a>
</div>